language: objective-c

osx_image: xcode8.3

xcode_project: Bumbo.xcodeproj
xcode_scheme: BumboTests

cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - brew outdated swiftlint || brew upgrade swiftlint
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - swiftlint
  - xcodebuild -project Bumbo.xcodeproj -scheme BumboTests -destination "platform=iOS Simulator,name=iPhone 6" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF ios -J Bumbo
